version: '3'
services:
  postgresql-zdg:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: izing
      POSTGRES_PASSWORD: password
      TZ: "America/Sao_Paulo"
    ports:
      - 5432:5432
    volumes:
      - /data:/var/lib/postgresql/datazdgizing

  redis-zdg:
    image: redis:latest
    command: redis-server --appendonly yes --requirepass "password"
    restart: always
    environment:
      TZ: "America/Sao_Paulo"
    ports:
      - 6379:6379

  rabbitmq-zdg:
    image: rabbitmq:3-management-alpine
    restart: always
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - /data:/var/lib/rabbitmq

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./backend/.env
    stdin_open: true
    tty: true
    depends_on:
      - redis-zdg
      - postgresql-zdg
      - rabbitmq-zdg
    ports:
      - "3100:3100"
      - "9229:9229"
    volumes:
      - .data/.wwebjs_auth:/app/.wwebjs_auth
      - .data/medias:/app/public
      - ./backend:/app 

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - api
    volumes:
      - ../.data/frontend:/app/dist/spa